baseUrl=https://parabank.parasoft.com/parabank/index.htm
registerUrl=https://parabank.parasoft.com/parabank/register.htm
browser=chrome
explicitWait=10
username=john
password=demo

error.emptyCredentials=Please enter a username and password.
error.invalidCredentials=The username and password could not be verified.
error.usernameExists=This username already exists.
error.firstNameRequired=First name is required.
error.lastNameRequired=Last name is required.